Feature: Educator Registration ValidationPage1

Scenario: C327 - Can you tell which page you are currently viewing in the breadcrumbs?
Given Launch the icivis educatorregistration URL
Then verify Current page count and print

Scenario: Do you see fields for Username, First Name, Last Name, E-mail address, and Verify email address?
Then Verify the text fields 

Scenario: Is a username pre-generated when you arrive on the page?
Then Verify username is pregenerated

Scenario: Can you select a button to randomly generate a new username in the field?
When refreshbutton beside username is clicked username generated by default

Scenario: Can you enter text in every field?
Then Enter text in all the fields

Scenario: Are required fields marked with an asterisk?
Then Validate all the fields have Asterisks

Scenario:If you hover over the email/verify email address fields, do you see a hover tooltip with appropriate text?
Then Hover on email/verifyemail and verify the result

Scenario: If you enter invalid information in a required field and select Next, do you receive an appropriate error message?
Then Enter invalid first name
And Enter invalid last name 
And Enter invalid email 
And Enter Invalid verify Email
Then click on next button 


Scenario: If you leave a required field blank and select Next, do you receive an appropriate error message?
Then enter all the fields except verifyemail, click on next button and verify error msg

Scenario: Do all error messages display correctly?
When  Validate click on next button error messages will display

Scenario: If you fill out all required fields with valid information and select Next, are you taken to Page 2?
Then Enter all the data in fields and click on next button 